onlinestore/config/routes.rb
Onlinestore::Application.routes.draw do

     resources :users, :sessions, :articles, :comments, :products
   get "sign_up" => "users#new", :as => "sign_up"
   get "log_in" => "sessions#new", :as => "log_in"
   get "log_out" => "sessions#destroy", :as => "log_out"
   get "list" => "products#list", :as => "list"

 	namespace :admin do
     resources :categories
   end

   root :to => 'users#index'

end

onlinestore/app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
  belongs_to :category

  validates :name, :presence => true
	validates :price, :presence => true, :numericality => true
  validates :category_id, :presence => true
end

onlinestore/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :require_login, :only => [:new, :create]
  before_filter :find_product_by_id, :only => [:edit, :update, :show, :destroy]
  before_filter :authenticate_edit, :only => [:edit, :update, :destroy]

	#listing all product
  def index
    @products = Product.order('updated_at DESC')
  end

	#form add new product
  def new
    @category = Category.order('parent_id')
    @product = Product.new
  end

	#process save new product
  def create
    @product = Product.new(params[:product]) 
    if @product.save 
      flash[:notice] = 'New Product Added ... ' 
      redirect_to products_path 
    else 
	    @category = Category.order('parent_id')
      render new_product_path 
    end  
  end
  
  #form edit product
  def edit
	    @category = Category.order('parent_id')
 	end
  
  #process update
  def update
   if @product.update_attributes(params[:product])
     flash[:notice] = 'Product Updated !' 
     redirect_to product_path(@product)
   else
	    @category = Category.order('parent_id')
     render :action => :edit
   end
  end

	#delete product
  def destroy
    @product.destroy
    redirect_to products_path
  end

	#show detail a product
  def show
		@category = @product.category
  end
 
	#listing by category(for homepage user use)
  def list
    if params[:id].nil?
	    redirect_to products_path
		else
	    @category = Category.find(params[:id])
			@products = @category.products
		end
  end

	#find selected product
  def find_product_by_id
    @product = Product.find(params[:id])
  end

	#authentication edit
  def authenticate_edit
	    if session[:user_id] != @product.user_id
       flash[:notice] = 'You are not authenticated user ... '
       redirect_to :action => :index
  		end
  end
end

onlinestore/app/helpers/products_helper.rb
module ProductsHelper
end

onlinestore/app/views/products/edit.html.erb
<h1> Edit Product </h1>
<table width="100%">
<%= form_for(@product) do |a| %>
  <% if @product.errors.any? %>
    <div id="errorExplanation">
      <h4>
         <%= pluralize(@product.errors.count, "error") %> prohibited this user from being saved:
      </h4>
        <% @product.errors.full_messages.each do |msg| %>
					<%= msg %><br/>
        <% end %>
    </div>
  <% end %>
	<tr> 
		<td> <%= a.label :name %></td>
		<td> :</td> <td> <%= a.text_field :name %> </td>
	</tr> <tr> 
		<td> <%= a.label :description %></td>
		<td> : </td> <td> <%= a.text_area :description, :rows => 6, :cols => 43 %></td>
	</tr> <tr> 
		<td> <%= a.label :price %> </td>
		<td> : </td> <td><%= a.text_field :price %></td>
	</tr> <tr> 
		<td> <%= a.label :weight %> </td>
		<td> : </td> <td><%= a.text_field :weight %></td>
	</tr> <tr> 
		<td> Category </td>
		<td> : </td> <td><%= a.select "category_id" , @category.map{|u| [u.category_tree, u.id]}, { :include_blank => '- Please Select -' } %> </td>
	</tr> <tr> 
  	<%= a.hidden_field :user_id, :value => session[:user_id] %>
		<td> <%= a.submit 'Update' %> <%= link_to 'Back', articles_path %> </td>
	</tr> <tr> 
<% end %>
</table>

onlinestore/app/views/products/index.html.erb
<h1>Listing Products</h1>
 <p> <i> <%= flash[:notice] %></i> </p>
<ul id="product">
  <% @products.each do |product| %>

    <li> Name : <%= product.name %> <br/>
    Price : <%= product.price %> <br/>
		<%= link_to 'See more', product_path(product),:method => :GET %>
		</li>
  <% end %>
</ul>

onlinestore/app/views/products/list.html.erb
<h1> <%= @category.name %> Products </h1>

<% if @products.empty? %>
	<p>	-- No Products for sale yet -- </p>
<% else %>
  <% @products.each do |product| %>
		<p>
    Name : <%= product.name %> <br/>
    Price : <%= product.price %> <br/>
		<%= link_to 'See more', product_path(product),:method => :GET %>
		</p>
  <% end %>
<% end %>

onlinestore/app/views/products/new.html.erb
<h1>New Product</h1>

<h3><%= flash[:error] %></h3>

<%= form_for @product do |a| %>
  <% if @product.errors.any? %>
    <div id="errorExplanation">
      <h4>
         <%= pluralize(@product.errors.count, "error") %> prohibited this user from being saved:
      </h4>
        <% @product.errors.full_messages.each do |msg| %>
          <%= msg %><br/>
        <% end %>
    </div>
  <% end %>

<table width="100%">
	<tr> 
		<td> <%= a.label :name %></td>
		<td> :</td> <td> <%= a.text_field :name %> </td>
	</tr> <tr> 
		<td> <%= a.label :description %></td>
		<td> : </td> <td> <%= a.text_area :description, :rows => 6, :cols => 43 %></td>
	</tr> <tr> 
		<td> <%= a.label :price %> </td>
		<td> : </td> <td><%= a.text_field :price %></td>
	</tr> <tr> 
		<td> <%= a.label :weight %> </td>
		<td> : </td> <td><%= a.text_field :weight %></td>
	</tr> <tr> 
		<td> Category </td>
		<td> : </td> <td><%= a.select "category_id" , @category.map{|u| [u.category_tree, u.id]}, { :include_blank => '- Please Select -' } %> </td>
	</tr> <tr> 
  	<%= a.hidden_field :user_id, :value => session[:user_id] %>
		<td> <%= a.submit 'Create' %> <%= link_to 'Back', articles_path %> </td>
	</tr> <tr> 
<% end %>
</table>

onlinestore/app/views/products/show.html.erb
<h1> Product </h1>

<p>	<% if !session[:user_id].nil? %>
			<% if session[:user_id] == @product.user_id %>
				<%= link_to 'Edit', edit_product_path(@product) %>
				<%= link_to 'Delete', @product, :method => :DELETE, :confirm => 'Are you sure?'%>
			<% end %>
		<% end %>
</p>

<p>
  <b>Category :</b> <%= @category.name %>
</p>
<p>
  <b>Name :</b> <%= @product.name %>
</p>
<p>
  <b>Description :</b> <%= @product.description %>
</p>
<p>
  <b>Price :</b> <%=@product.price %>
</p>
<p>
  <b>Weight :</b> <%=@product.weight %>
</p>