onlinestore/config/routes.rb
Onlinestore::Application.routes.draw do

     resources :users, :sessions, :articles, :comments, :products
   get "sign_up" => "users#new", :as => "sign_up"
   get "log_in" => "sessions#new", :as => "log_in"
   get "log_out" => "sessions#destroy", :as => "log_out"
   get "list" => "products#list", :as => "list"

 	namespace :admin do
     resources :categories
   end

   root :to => 'users#index'

end

onlinestore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onlinestore</title>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<header> 
		 Welcome to my store
	</header>
	<nav>
		<ul>
			<% if session[:user_id].nil? %>
			<li> <%= link_to 'Sign Up', sign_up_path %> </li>
			<% else %>
			<li> <%= link_to 'Home', root_url %> </li>
			<% end %>
			<li> <%= link_to 'Products', products_path %> </li>
			<li> <%= link_to 'Article', articles_path %> </li>
			<% if session[:email] == 'admin@admin.com' %>
			<li> <%= link_to 'Category', admin_categories_path %> </li>
			<% end %>
			<div class="clear" </div>
		</ul>
	</nav>

	<div class="leftside"> 
			<ul>
				<% if session[:user_id].nil? %>				
					<h2>Log in</h2> 
				 	
					  <%= form_tag sessions_path do %> 
					  <p> 
					    <%= label_tag :email %><br /> 
					    <%= text_field_tag :email, params[:email], :size => 15 %> 
					  </p> 
					  <p> 
					    <%= label_tag :password %><br /> 
					    <%= password_field_tag :password, '', :size => 15 %> 
					  </p> 
					  <p class="button"><%= submit_tag 'Login' %></p> 
					<% end %> 
				<% else %>
				<li> <%= link_to 'Edit Profile', edit_user_path(session[:user_id]) %> </li>
				<li> <%= link_to 'Sell a Product', new_product_path %> </li>
				<li> <%= link_to 'Share an Article', new_article_path %> </li>
				<li> <%= link_to 'Logout', log_out_path %> </li>
			</ul>

			<div id="category">
				<% if session[:email] != 'admin@admin.com'%>
					<h3> List Category </h3>
						<% Category.all.each do |c| %>
							<% if c.parent_id.nil?%>
								<p class = "parent"> <%= link_to c.name, list_path(:id => c.id) %> </p>
							<% else%>
								<p class = "child"> <%= link_to c.name, list_path(:id => c.id) %> </p>
							<% end %>
		  			<% end %>
				<% end %>	
			</div>
			<% end %>
	</div>

	<div class="rightside"> 
		<%= yield %>
	</div>
  <div class="clear"> </div>
</div>
</body>
</html>

onlinestore/app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onlinestore</title>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<header> 
		 Welcome to my store
	</header>
	<nav>
		<ul>
			<li> <%= link_to 'Sign Up', sign_up_path %> </li>
			<li> <%= link_to 'Products', products_path %> </li>
			<li> <%= link_to 'Article', articles_path %> </li>
			<div class="clear"> </div>
		</ul>
	</nav>

	<div class="leftside">
		<div id = "login" >
		<%= yield %>
		</div>
	</div>

	<div class="rightside"> 
		<h1> Listing Product </h1>
		<ul id="product">
				<% Product.find_by_sql("SELECT * FROM `products` ORDER BY `updated_at` DESC LIMIT 6 " ).each do |p| %>
					<li> Name : <%= p.name %> <br/>
							Price : <%= p.price %><br/>
							<%= link_to 'See more', product_path(p.id),:method => :GET %>
					</li>
				<% end %>
				<div class="clear"></div>
		</ul>
		<h1> Latest Article </h1>
			<% Article.find_by_sql("SELECT * FROM `articles` ORDER BY `updated_at` DESC LIMIT 3 " ).each do |a| %>
				<article> 
					<p> <%= truncate(a.body, :length => 20) %> </p>
					<p> <%= link_to 'Read more', article_path(a.id),:method => :GET %> </p>
    		</article>
			<% end %>
	</div>
	<div class="clear"> </div>
</div>
</body>
</html>