demo/config/routes.rb
Demo::Application.routes.draw do
  get "sessions/new"

  get "users/new"

  get "articles/index"

  get "say/hello"

  get "say/goodbye"

     resources :articles, :users, :sessions, :comments

   root :to => 'users#new'
   get "sign_up" => "users#new", :as => "sign_up"
   get "log_in" => "sessions#new", :as => "log_in"
   get "log_out" => "sessions#destroy", :as => "log_out"

  
   namespace :admin do
     resources :articles
   end

end

demo/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  belongs_to :user

  scope :rating_is_and_above, lambda {|rating| where("rating >= ?", rating) }

  validates :title, :presence => true, :uniqueness => true
end

demo/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_filter :require_admin_login
  before_filter :find_article_by_id, :only => [:edit, :update, :destroy]

  def index
    @admin_articles = Article.all
  end

  def new
    @admin_article = Article.new
  end

  def create
    @admin_article = Article.new(params[:article]) 
    if @admin_article.save 
      flash[:notice] = 'New Article Added ... ' 
      redirect_to admin_articles_path
    else 
      render "new"
    end  
  end

  def edit
	end
  
  def update
  	if @admin_article.update_attributes(params[:article])
      flash[:notice] = 'Article Updated !' 
      redirect_to admin_articles_path
    else
      render "edit"
    end
  end

  def destroy
    @admin_article.destroy
    redirect_to admin_articles_path
  end

	#find article by id
  def find_article_by_id
    @admin_article = Article.find(params[:id])
  end
end

demo/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   before_filter :require_login, :only => [:new, :create, :edit, :update, :delete]
   before_filter :find_article_by_id, :only => [:edit, :update, :destroy, :show]
 
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article]) 
    if @article.save 
      flash[:notice] = 'New Article Added ... ' 
      redirect_to articles_path 
    else 
      render "new" 
    end  
  end
  
  def edit; end
  
  def update
   if @article.update_attributes(params[:article])
     flash[:notice] = 'Article Updated !' 
     redirect_to articles_path
   else
     render :action => :edit
   end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  def show
    @comments = @article.comments
    @comment = Comment.new
  end

  def find_article_by_id
    @article = Article.find(params[:id])
    if session[:user_id] != @article.user_id
       flash[:notice] = 'You are not authenticated user ... '
       redirect_to :action => :index
    end
  end

end

demo/app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

demo/app/helpers/articles_helper.rb
module ArticlesHelper
end

demo/app/views/articles/_comments.html.erb
<% @comments.each do |comment| %>
  <%= comment.content %><br /> 
<% end %>

demo/app/views/articles/edit.html.erb
<h1> Edit Article </h1>

<%= form_for(@article) do |a| %>
  <% if @article.errors.any? %>
    <div id="errorExplanation">
      <h4>
         <%= pluralize(@article.errors.count, "error") %> prohibited this user from being saved:
      </h4>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= a.label :title %>
<%= a.text_field :title %> <br>
<%= a.label :body %>
<%= a.text_area :body %><br>
<%= a.label :user_id %>
<%= a.text_field :user_id %> <br>
<%= a.submit %>
<% end %>

<%= link_to 'Back', articles_path %>

demo/app/views/articles/index.html.erb
<h1>Article Lists</h1>
 <p> <i> <%= flash[:notice] %></i> </p>

<table>
  <tr>
    <th> Title </th>
    <th> Body </th>
    <th> User Id </th>
    <th>  </th>
  </tr>
  <% @articles.each do |article| %>
  <tr> 
    <td> <%= article.title %> </td>
    <td> <%= article.body %> </td>
    <td align="center"> <%= article.user_id %> </td>
    <td> 
      <%= link_to 'Show', article %>
      <%= link_to 'Edit', edit_article_path(article) %>
      <%= link_to 'Delete', article, :method => :delete %>
    </td>
  </tr>
  <% end %>
</table>

<%= link_to 'New Article', new_article_path %>

  

demo/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for(@article) do |a| %>
  <% if @article.errors.any? %>
    <div id="errorExplanation">
      <h4>
         <%= pluralize(@article.errors.count, "error") %> prohibited this user from being saved:
      </h4>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= a.label :title %>
<%= a.text_field :title %> <br>
<%= a.label :body %>
<%= a.text_area :body %><br>
<%#= a.label :user_id %>
<%= a.hidden_field :user_id, :value => session[:user_id] %> <br>
<%= a.submit %>
<% end %>

<%= link_to 'Back', articles_path %>

demo/app/views/articles/show.html.erb
<h1> Article </h1>

<p>
  <b>Title :</b> <%= @article.title %>
</p>
<p>
  <b>Body :</b> <%= @article.body %>
</p>
<p>
<p>
  <b>User id :</b> <%= @article.user_id %>
</p>

<p><%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %> </p>


<div id="comments">
Comments : <br/>
   <%= render :partial => "comments", :locals => {:comments => @comments}  %>
</div><br /><br />


<% unless(current_user.nil?)%>
 <%= form_for @comment, :url => comments_path, :remote => true do |c| %>
  <% if @comment.errors.any? %>
    <div id="errorExplanation">
      <h4>
         <%= pluralize(@comment.errors.count, "error") %> prohibited this user from being saved:
      </h4>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= c.text_area :content, :rows => 6%><br>
<%= c.hidden_field :article_id, :value => @article.id %>
<%= c.submit %>
<% end %>
<% end %>